<a href="https://colab.research.google.com/github/pascale25/Deep_learning/blob/master/pytorch_00_Mireille.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

1.12.1+cu113


In [2]:
torch.cuda.is_available()

False

In [3]:
torch.cuda?

In [4]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [5]:
### introduction to tensor

In [6]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
vector = torch.tensor([7,7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
Matrix = torch.tensor([[7,8], [9,10]])

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
Matrix.ndim

2

In [15]:
# Tensor
Tensor = torch.tensor([[[1,2,3], [3,6,7], [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [16]:
Tensor.ndim

3

In [17]:
Tensor.shape

torch.Size([1, 3, 3])

In [18]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

In [19]:
# practice Tensor shape, ndim
Tensor1 = torch.tensor([[[[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55],
                           [3,4,6]]]]])

In [20]:
print(Tensor1.shape)
print(Tensor1.ndim)

torch.Size([1, 1, 1, 5, 3])
5


In [21]:
# practice Tensor shape, ndim
Tensor2 = torch.tensor([[[[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55]]]]])

In [22]:
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [23]:
# practice Tensor shape, ndim
Tensor3 = torch.tensor([[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55]]])

In [24]:
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [25]:
# practice Tensor shape, ndim
Tensor4 = torch.tensor([[[1,2,4], [2,3,45], [3,4,55]]])
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [26]:
### random tensor
W = torch.rand(2,2,3)
W

tensor([[[0.7737, 0.2191, 0.9548],
         [0.0700, 0.3883, 0.6718]],

        [[0.0326, 0.6472, 0.2436],
         [0.4854, 0.2410, 0.6167]]])

In [27]:
print(W.ndim)
print(W.shape)

3
torch.Size([2, 2, 3])


In [28]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color(R,B,G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [31]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [33]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [36]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [37]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [38]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [39]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [41]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)