<a href="https://colab.research.google.com/github/pascale25/Deep_learning/blob/master/pytorch_00_Mireille.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

1.12.1+cu113


In [2]:
torch.cuda.is_available()

False

In [3]:
torch.cuda?

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
### introduction to tensor

In [4]:
# scalar a zero dimention tensor
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [6]:
# check dimention with ndim attribute
scalar.ndim

0

In [5]:
scalar.item()

7

In [ ]:
# vector a single dimention tensor
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
Matrix = torch.tensor([[7,8], [9,10]])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
Matrix.ndim

2

In [8]:
# Tensor
Tensor = torch.tensor([[[1,2,3], [3,6,7], [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [9]:
Tensor.ndim

3

In [10]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

In [ ]:
# practice Tensor shape, ndim
Tensor1 = torch.tensor([[[[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55],
                           [3,4,6]]]]])

In [ ]:
print(Tensor1.shape)
print(Tensor1.ndim)

torch.Size([1, 1, 1, 5, 3])
5


In [ ]:
# practice Tensor shape, ndim
Tensor2 = torch.tensor([[[[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55]]]]])

In [ ]:
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [ ]:
# practice Tensor shape, ndim
Tensor3 = torch.tensor([[[1,2,4], 
                           [2,3,45], 
                           [44,6,8],
                           [3,4,55]]])

In [ ]:
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [ ]:
# practice Tensor shape, ndim
Tensor4 = torch.tensor([[[1,2,4], [2,3,45], [3,4,55]]])
print(Tensor2.shape)
print(Tensor2.ndim)

torch.Size([1, 1, 1, 4, 3])
5


In [ ]:
### random tensor
W = torch.rand(2,2,3)
W

tensor([[[0.7737, 0.2191, 0.9548],
         [0.0700, 0.3883, 0.6718]],

        [[0.0326, 0.6472, 0.2436],
         [0.4854, 0.2410, 0.6167]]])

In [ ]:
print(W.ndim)
print(W.shape)

3
torch.Size([2, 2, 3])


In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color(R,B,G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [14]:
# creating a range of tensor and Tensor Like Other Tensors
A = torch.arange(1,11)
B = torch.arange(start = 0, end=1000, step=77)
print(A)
print(B)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [15]:
# creating tensors like (the same shape as A)
like_A = torch.zeros_like(A)
like_A

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data type

In [22]:
# Flaot 32 tensor (precision in computing)
float_32 = torch.tensor([3, 6.2, 9.2],
                        dtype= None,
                        device=None,
                        requires_grad=False)
float_32

tensor([3.0000, 6.2000, 9.2000])

In [17]:
float_32.dtype

torch.float32

In [19]:
# convert to float 16
float_16 = float_32.type(torch.float16)
float_16.dtype

torch.float16

In [21]:
AA = float_32 * float_16
AA.dtype

torch.float32

In [ ]:
int_32 = torch.tensor([2,4,5], dtype=torch.long)


## tensor information
 - shape or size
 - device
 - datatype

In [23]:
Tensor = torch.rand(3,4)
Tensor

tensor([[0.1225, 0.0167, 0.6022, 0.7499],
        [0.9805, 0.9513, 0.8322, 0.8428],
        [0.6997, 0.0229, 0.8822, 0.3219]])

In [24]:
Tensor.size(), Tensor.shape, Tensor.dtype, Tensor.device

(torch.Size([3, 4]), torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Manipulating Tensor 

In [25]:
## Tensor operation - addition, subtraction, multiplication, division
# Matrix multiplication 
# creat a tensor
Tensor = torch.tensor([1,2,3])
Tensor + 10

tensor([11, 12, 13])

In [26]:
Tensor * 10

tensor([10, 20, 30])

In [27]:
Tensor - 10

tensor([-9, -8, -7])

In [28]:
# Pytorch in built functions
torch.mul(Tensor, 10)

tensor([10, 20, 30])

In [29]:
torch.add(Tensor, 10)

tensor([11, 12, 13])

In [33]:
# matrix multiplication
%%time 
torch.matmul(Tensor, Tensor)

CPU times: user 992 µs, sys: 949 µs, total: 1.94 ms
Wall time: 1.84 ms


tensor(14)

In [34]:
Tensor @ Tensor

tensor(14)

### Matrix multiplication 

In [31]:
Tensor * Tensor

tensor([1, 4, 9])

In [32]:
# matrix multiplication
1*1 + 2*2 + 3*3

14

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [35]:
torch.rand(3,2)

tensor([[0.4325, 0.1981],
        [0.8371, 0.6265],
        [0.2189, 0.8580]])

In [37]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) # Inner dimension is 2 and 3 
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: ignored

In [39]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)) # Inner dimension is 2 and 2 
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

tensor([[0.8058, 0.9717, 0.7403],
        [0.3582, 0.4224, 0.3268],
        [0.1571, 0.2895, 0.1684]])

In [40]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [42]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))
torch.matmul(torch.rand(3,10), torch.rand(10,3)).shape

torch.Size([3, 3])

In [44]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1,2], 
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # torchmm is the same as torch.matmul # alias 


RuntimeError: ignored

In [47]:
# How to ajust the shape 
# to fixe the shape of tensor 
# we can transpose (it switches the axes or dimensions of a given tensor)
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [48]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [50]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [84]:
tensor_A = torch.rand([6,2])
tensor_A

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414],
        [0.2969, 0.8317],
        [0.1053, 0.2695],
        [0.3588, 0.1994],
        [0.5472, 0.0062]])

In [85]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([6, 2])

Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971],
        [ 0.7375,  0.2534,  0.3631, -0.0242,  0.4709,  0.2049],
        [ 0.8334,  0.1658,  0.3138, -0.1406,  0.6653,  0.3514],
        [ 0.8218,  0.0091,  0.2571, -0.2857,  0.8830,  0.4416]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([6, 6])


### Tensor aggregation min, max, mean, sum, 

In [89]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [91]:
torch.mean(x)

RuntimeError: ignored

In [92]:
x.dtype

torch.int64

In [93]:
x1 = x.type(torch.float32)
x1, x1.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [94]:
torch.mean(x1)

tensor(45.)

In [95]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the position Min and Max

In [96]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
x.argmax()

tensor(9)

In [98]:
x.argmin()

tensor(0)

In [99]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### reshaping, stacking, squeezing, and unsqueezing tensors

In [101]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [102]:
# add an extra dimension
x_reshape = x.reshape(1,7)
x_reshape, x_reshape.shape

RuntimeError: ignored

In [104]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [105]:
x_reshape = x.reshape(2,9)

RuntimeError: ignored

In [106]:
x_reshape = x.reshape(9,1)
x_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [114]:
xx = torch.arange(1., 11.)
xx,  xx.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [117]:
xx.reshape(1,10), xx.reshape(10, 1), xx.reshape(2, 5),

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]), tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]), tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]))

In [119]:
# change the view
z  = xx.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [122]:
#z and xx share the same memory as the original 
z[:, 0] = 5
z, xx

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [124]:
# stack 
x_stacked = torch.stack([x,x,x,x], dim=0) # it is Vstack (vertival stack)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [125]:
# stack 
x_stacked = torch.stack([x,x,x,x], dim=1) #hstack (horizontal)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [135]:
# Squeeze and unsqueeze
x, x.reshape(1,9), x.reshape(1,9).shape,  x.reshape(1,9).squeeze(), x.reshape(1,9).squeeze().shape, x.reshape(1,9).squeeze().squeeze(), x.reshape(1,9).squeeze().squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [142]:
y = x.reshape(1,9)
y.unsqueeze(dim=0)

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [143]:
y.unsqueeze(dim=1)

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [146]:
# torcj.permute
img = torch.rand(size =(224, 224, 3)) # (h, w, c)
img_permute = img.permute(2,0,1) # (c, h, w)
img.shape, img_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selectin data from tensors)

In [148]:
import torch 
x  = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [149]:
x[0] # dim = 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
x[0][0]

tensor([1, 2, 3])

In [153]:
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [155]:
x[:,0]

tensor([[1, 2, 3]])

In [156]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [158]:
x[:, 1, 1]

tensor([5])

### numpy to tensor

In [159]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [160]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###  redproducibility

In [161]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2012, 0.1478, 0.3702, 0.1441],
        [0.1284, 0.2582, 0.7732, 0.1060],
        [0.6737, 0.3027, 0.9716, 0.3592]])

Tensor B:
tensor([[0.6261, 0.9557, 0.0057, 0.6767],
        [0.2114, 0.3975, 0.4007, 0.9157],
        [0.0821, 0.8882, 0.4257, 0.2228]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [162]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Accesing a GPU in pytorch

In [1]:
!nvidia-smi

Tue Nov  8 03:50:41 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [6]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [7]:

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [9]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exo


In [11]:
torch.cuda.is_available()

True

In [12]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [13]:
x = torch.tensor([2,3,5])
x

tensor([2, 3, 5])

In [16]:
x[0].item()

2

In [27]:
import torch

torch.rand(2,5, 2),  torch.rand(2,5,2).shape

(tensor([[[0.8284, 0.6644],
          [0.4471, 0.9063],
          [0.0035, 0.4029],
          [0.5627, 0.3123],
          [0.3200, 0.9470]],
 
         [[0.8975, 0.0605],
          [0.0125, 0.2672],
          [0.8171, 0.1381],
          [0.6466, 0.9080],
          [0.1486, 0.5327]]]), torch.Size([2, 5, 2]))

In [19]:
torch.rand(3)

tensor([0.4287, 0.2883, 0.9726])

In [20]:
torch.rand(3,4)

tensor([[0.8408, 0.0890, 0.2121, 0.4128],
        [0.8764, 0.5828, 0.0843, 0.6277],
        [0.2991, 0.2871, 0.7277, 0.5695]])

In [29]:
torch.matmul(torch.rand(2,4), torch.rand(4, 6))

tensor([[1.0276, 1.2751, 1.3419, 1.3403, 1.7758, 1.8116],
        [0.9167, 1.1532, 1.1372, 1.0246, 1.4102, 1.5685]])

In [32]:
#random.seed(0)
torch.manual_seed(0)
z = torch.rand(7,1)
z

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [35]:
z.reshape(1,7)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [37]:
torch.matmul(z, z.reshape(1,7)).shape

torch.Size([7, 7])

In [39]:
y = torch.rand(size = (1,7))
y, y.T

(tensor([[0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816]]),
 tensor([[0.2939],
         [0.5185],
         [0.6977],
         [0.8000],
         [0.1610],
         [0.2823],
         [0.6816]]))

In [40]:
torch.matmul(y, y.T)

tensor([[2.0522]])

In [42]:
# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
         [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
         [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
         [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
         [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995]]),
 torch.Size([7, 7]))

In [43]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[0.7086],
         [1.4788],
         [1.5589],
         [1.9608],
         [1.4400],
         [1.8606],
         [2.0540]]), torch.Size([7, 1]))

In [ ]:

torch.manual_seed()

In [ ]:
## # Set random seed on the GPU
torch.cuda.manual_seed(1234)